version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: super-gestao  # Nome da imagem personalizada
    ports:
      - "8080:8080"
    command: php artisan serve --host=0.0.0.0 --port=8080
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data  # Caminho relativo para o subdiretório dentro da pasta do projeto
    networks:
      - mynetwork
 
networks:
  mynetwork:
 
volumes:
  pg_data:
