version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: super-gestao  # Nome da imagem personalizada
    ports:
      - "8080:8080"
    command: php artisan serve --host=0.0.0.0 --port=8080
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: secret

  db:
    image: pgsql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
